import argparse

class Parser:
    def __init__(self):
        """
        Init function.
        Params: None
        """
        self.parser = argparse.ArgumentParser()
        # The type of attack to run
        self.parser.add_argument('--mode', default='aia', choices=['aia', 'mia'], help="Running the code with different attack scenarios. 'aia' means attribute inference, and 'mia' means membership inference.")

        # Dataset of interest
        self.parser.add_argument('--dataset', type=str, default='ppmf', help = "The folder that holds the datasets of interest, aggregate statistics and domains")
        self.parser.add_argument('--filenames', type=str, nargs="*", default=['ppmf_011250112001017'], help = "The actual csv filename of dataset of interest")
        self.parser.add_argument('--test-size', type=int, default=450, help = "The number of records of test-dataset that sampled from the full dataset")

        # Auxiliary dataset
        self.parser.add_argument('--aux-type', type=str, default='real', choices=['real', 'syn'], help="Select the type of aux dataset. 'real' means the aux dataset is another split from the same block. 'syn' means the aux dataset is generated by synthetic generator.")

        # Aggregate statistics
        self.parser.add_argument('--seed', type=int, default=0)
        self.parser.add_argument('--num-aggregates', type=int, default=113, help = "The number of released aggregates")
        
        # Device
        self.parser.add_argument('--chosen-gpus', nargs="*", type=int, default=-1, help = "The list of chosen GPUs by GPU device indexs")
        self.parser.add_argument('--multi-cpus', type=int, default=1, help = "Run processes in multiple CPUs if the value not None and greater than 1")

        # Noise addition to aggregates
        self.parser.add_argument('--noise-seed', type=int, default=0)
        self.parser.add_argument('--noise-budget', type=float, default=None, help = "Per-aggregate privacy budget for Laplace noise in AIA. If omitted (None), AIA uses clean aggregates.")

        # Attack model
        self.parser.add_argument('--note', type=str, default='')
        attack_subparsers = self.parser.add_subparsers(dest = "attack")

        # RAP method
        rap_parser = attack_subparsers.add_parser("rap", help = "Parse arguments for RAP attacks only")
        rap_parser.add_argument('--num-models', type=int, default=100, help='# runs of RAP-RANK to train')
        rap_parser.add_argument('--warm-start', action='store_true', help = "Initialize the synthetic generator with auxiliary knowledge, not by random.")

        # CIP method
        cip_parser = attack_subparsers.add_parser("cip", help = "Parse arguments for CIP-based attacks only")
        cip_parser.add_argument('--init-solver', action='store_true', help = "Initialize the CSP solver with auxiliary knowledge, not by random.")
        cip_parser.add_argument('--num-solutions', type=int, default=100, help="The maximum number of feasible solution of primal problem returned by the solver")

        # DeSIA Method
        desia_parser = attack_subparsers.add_parser("desia", help = "Parse arguments for DeSIA")
        desia_parser.add_argument('--stochastic-method', choices=['stochastic-method', "threshold"], help = "Assign the method for the second step to predict labels of non-determined records")
        desia_parser.add_argument('--num-training-qbses', type=int, default=20000, help = "The number of shadow datasets of the stochastic module")
        desia_parser.add_argument('--aia-model', type=str, default="logit", choices = ["logit", 'mlp', 'svm', 'rf'], help="The classifier used by the stochastic module")

    def parse_cmdline_args(self):
        """
        Parse the arguments from a command line arguments.
        Params: None
        Return: 
            The parsed arguments
        """
        args = self.parser.parse_args()
        return args
    
    def parse_input_args(self, input_args: list):
        """
        Parse the arguments from a list-type variable in python script.
        Params: 
            input_args: The list of input arguments.
        Return: 
            The parsed arguments
        """
        self.args = self.parser.parse_args(input_args)
        return self.args
